version: "3"

services:
  nginx:
    ports:
      - "80:80"
  node-app:
    deploy:
      replicas: 8
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 15s
    build: 
      args:
        NODE_ENV: production
    # ports:
    #   - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - ME_CONFIG_MONGODB_URL=${ME_CONFIG_MONGODB_URL}
      - SESSION_SECRET=${SESSION_SECRET}
    command:
      npm run start:prod
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}