version: "3"

services:
  node-app:
    build: .
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db'
  redis: 
    image: redis
    
volumes:
  mongo-db:
  
# docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build
# docker compose -f docker-compose.yml -f docker-compose.dev.yml down
# docker exec -it proper-node-docker-node-app-1 sh
# docker logs proper-node-docker-node-app-1 -f